// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB9Qz4-bTtAs6D8nWGmWIzNdfRc71TbOM',
    appId: '1:189853637011:web:4f8d49c30a46cd3eee7066',
    messagingSenderId: '189853637011',
    projectId: 'sheress-a5a57',
    authDomain: 'sheress-a5a57.firebaseapp.com',
    storageBucket: 'sheress-a5a57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8wEN3wEDvdqhD0aFVdHDBHSrYklcpB4',
    appId: '1:189853637011:android:001f4095bccb664bee7066',
    messagingSenderId: '189853637011',
    projectId: 'sheress-a5a57',
    storageBucket: 'sheress-a5a57.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB9Qz4-bTtAs6D8nWGmWIzNdfRc71TbOM',
    appId: '1:189853637011:web:c6afe5f22eccaa4dee7066',
    messagingSenderId: '189853637011',
    projectId: 'sheress-a5a57',
    authDomain: 'sheress-a5a57.firebaseapp.com',
    storageBucket: 'sheress-a5a57.firebasestorage.app',
  );
}
